name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: set up JDK 1.8
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'temurin'
        java-version: '21'
