name: Auto Merge
on:
  workflow_dispatch:
    inputs:
      PR_URL:  
        description: 'Pull Request URL'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto Merge on PR
        run: |
          gh pr merge "$PR_URL" --auto --squash
        env:
          PR_URL: ${{inputs.PR_URL}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}