### .github/workflows/dependabot_pr.yml
### This workflow doesn't have access to secrets and has a read-only token
name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot"
      - name: Add a label for all approved dependencies
        if: success()
        run: |
            gh pr merge "$PR_URL" --auto --squash
        env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GH_TOKEN: ${{secrets.GH_TOKEN}}