### .github/workflows/dependabot_pr.yml
### This workflow doesn't have access to secrets and has a read-only token
name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 4m
        run: |
          sleep 4m